name: Deploy Infra

on: push

env:
  AWS_REGION: eu-central-1
  IAM_ROLE: arn:aws:iam::160071257600:role/gg-iac-lab--github-actions-role

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: TFLint Setup
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.56.0

      - name: Terraform Validate
        run: |
          cd session_6
          terraform fmt --recursive
          tflint --recursive
          terraform validate

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        run: |
          cd session_6
          terraform init
      
      - name: Terraform Plan
        run: |
          cd session_6
          terraform plan -var-file="dev.tfvars"
      
      - name: Terraform Apply
        run: |
          cd session_6
          terraform apply -auto-approve -var-file="dev.tfvars"
