name: Destroy Infra

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  IAM_ROLE: arn:aws:iam::160071257600:role/gg-iac-lab--github-actions-role

jobs:
  deploy:
    name: Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Initialize Terraform
        run: |
          cd session_6
          terraform init

      - name: Destroy
        run: |
          cd session_6
          terraform destroy -auto-approve -var-file="dev.tfvars"
